<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Numos.Maths</RootNamespace>
        <PackageId>Numos.Maths</PackageId>
        <Title>Numos Maths</Title>
        <Description>Mathematical primitives used by Numos.</Description>
        <PackageTags>simulation;mathematics;voxel;nativeaot</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
