<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Numos.Collections</RootNamespace>
        <PackageId>Numos.Collections</PackageId>
        <Title>Numos Collections</Title>
        <Description>Collections used by Numos.</Description>
        <PackageTags>simulation;collections;voxel;nativeaot</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Numos.Maths\Numos.Maths.csproj" />
    </ItemGroup>
    
</Project>
