<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nod3r.Collections\Nod3r.Collections.csproj"/>
        <ProjectReference Include="..\Numos.Collections\Numos.Collections.csproj"/>
        <ProjectReference Include="..\Numos.Maths\Numos.Maths.csproj"/>
    </ItemGroup>
    
</Project>
